In [1]:
#PyBank homework exercise 1. Name: Benjamin Weymouth 

In [2]:
#import required libraries 
import csv
from pathlib import Path
import numpy as np 

In [3]:
# set up the file path 
csvpath = Path('./Resources/budget_data.csv')
csvpath

WindowsPath('Resources/budget_data.csv')

In [4]:
# Initialize lists to hold data 

dates = []
profit_losses = []

In [5]:
# use open method to open csvpath 
with open(csvpath, 'r') as csvfile:

    # check datatype 
    print(type(csvfile))

    # set up csv.reader, specify a delimiter 
    csvreader = csv.reader(csvfile, delimiter=',')
    # check csv datatype 
    print(type(csvreader))
        
    # skip over header
    header = next(csvreader)
    print(header)
    
    #read in data into a list object 
    for row in csvreader:
        # date variable equal to date row values 
         
        date = row[0]
        # Append the row date value to the list of dates
        dates.append(date)
        #set profit_loss value and casting to an integer 
        profit_loss = int(row[1])
        profit_losses.append(profit_loss)      
    

<class '_io.TextIOWrapper'>
<class '_csv.reader'>
['Date', 'Profit/Losses']


In [6]:
#initialize Variables for total and count 

total_profit_losses = 0
count_profit_losses = 0

#use profit_losses list to find total and count 

for profit_loss in profit_losses:

    # Sum the total and count variables
    total_profit_losses += profit_loss
    count_profit_losses += 1

#for testing purposes, printing values of variables 
print(total_profit_losses)  
print(count_profit_losses)
 

38382578
86


In [7]:
#Find the total number of months included in the dataset.
#using the built in "len" method 
total_months = len(dates)

total_months

86

In [8]:
#list holding only the profits and losses 
profit_losses

[867884,
 984655,
 322013,
 -69417,
 310503,
 522857,
 1033096,
 604885,
 -216386,
 477532,
 893810,
 -80353,
 779806,
 -335203,
 697845,
 793163,
 485070,
 584122,
 62729,
 668179,
 899906,
 834719,
 132003,
 309978,
 -755566,
 1170593,
 252788,
 1151518,
 817256,
 570757,
 506702,
 -1022534,
 475062,
 779976,
 144175,
 542494,
 359333,
 321469,
 67780,
 471435,
 565603,
 872480,
 789480,
 999942,
 -1196225,
 268997,
 -687986,
 1150461,
 682458,
 617856,
 824098,
 581943,
 132864,
 448062,
 689161,
 800701,
 1166643,
 947333,
 578668,
 988505,
 1139715,
 1029471,
 687533,
 -524626,
 158620,
 87795,
 423389,
 840723,
 568529,
 332067,
 989499,
 778237,
 650000,
 -1100387,
 -174946,
 757143,
 445709,
 712961,
 -1163797,
 569899,
 768450,
 102685,
 795914,
 60988,
 138230,
 671099]

In [9]:
#using the diff method in order to compute all changes in profit/losses
#diff provides a list with all the differences 

#Official Documentation for reference: https://numpy.org/doc/stable/reference/generated/numpy.diff.html

differences  = np.diff(profit_losses)
#the numpy array "differences" now holds a numpy array of all differences / changes in profit/losses
differences

array([  116771,  -662642,  -391430,   379920,   212354,   510239,
        -428211,  -821271,   693918,   416278,  -974163,   860159,
       -1115009,  1033048,    95318,  -308093,    99052,  -521393,
         605450,   231727,   -65187,  -702716,   177975, -1065544,
        1926159,  -917805,   898730,  -334262,  -246499,   -64055,
       -1529236,  1497596,   304914,  -635801,   398319,  -183161,
         -37864,  -253689,   403655,    94168,   306877,   -83000,
         210462, -2196167,  1465222,  -956983,  1838447,  -468003,
         -64602,   206242,  -242155,  -449079,   315198,   241099,
         111540,   365942,  -219310,  -368665,   409837,   151210,
        -110244,  -341938, -1212159,   683246,   -70825,   335594,
         417334,  -272194,  -236462,   657432,  -211262,  -128237,
       -1750387,   925441,   932089,  -311434,   267252, -1876758,
        1733696,   198551,  -665765,   693229,  -734926,    77242,
         532869])

In [10]:
#Use max method for the greatest increase in profits over the entire period.
greatest_increase_profits = max(differences)
greatest_increase_profits


1926159

In [11]:
#Use min method for the greatest decrease in profits over the entire period.
greatest_decrease_profits = min(differences)
greatest_decrease_profits

-2196167

In [12]:
#Use average method for the average change in profits over the entire period.
average_change = np.average(differences)
average_change

-2315.1176470588234

In [13]:
#use Index to match value with month 
#Find index of the Greatest Increase in Profits 
max_index = np.where(differences == greatest_increase_profits)
print(max_index) 

#Find index of the Greatest Decrease in Profits 
min_index = np.where(differences == greatest_decrease_profits)
print(min_index) 

#Check length of each list. Dates has one more value than Differences list, so we add one to the index
print(len(differences))
print(len(dates))

#Match up values index to Dates List 

max_date = dates[25]
min_date = dates[44]

(array([24], dtype=int64),)
(array([43], dtype=int64),)
85
86
Feb-2012
Sep-2013


In [16]:
#print the analysis to the terminal 

print("Financial Analysis")
print("----------------------------")
print(f"Total Months: {total_months}")
print(f"Total: ${total_profit_losses}")
print(f"Average  Change: ${round(average_change, 2)}")
print(f"Greatest Increase in Profits: {max_date} (${greatest_increase_profits})")
print(f"Greatest Decrease in Profits: {min_date} (${greatest_decrease_profits})")

Financial Analysis
----------------------------
Total Months: 86
Total: $38382578
Average  Change: $-2315.12
Greatest Increase in Profits: Feb-2012 ($1926159)
Greatest Decrease in Profits: Sep-2013 ($-2196167)


In [15]:
# export a text file with the results.
output_file = Path('./Resources/output.txt')

# use file.write to output to the file. 
with open(output_file, 'w') as file:
    file.write("Financial Analysis\n")
    file.write("----------------------------\n")
    file.write(f"Total Months: {total_months}\n")
    file.write(f"Total: ${total_profit_losses}\n")
    file.write(f"Average  Change: ${round(average_change, 2)}\n")
    file.write(f"Greatest Increase in Profits: {max_date} (${greatest_increase_profits})\n")
    file.write(f"Greatest Decrease in Profits: {min_date} (${greatest_decrease_profits})")